### ISSUE TITLE
Creation of the Docker container fails due to reboot requirement

### ISSUE THREAD

**Issue by BCSharp** [IronLanguages/ironclad#16]
When creating a Docker image using command
```
docker build -t ironclad-build:v3.4wip -m 2GB .
```
the following error occurs:

```
Step 6/8 : RUN Set-ExecutionPolicy Bypass -Scope Process -Force;     [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;     iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'));         choco install -y python3
 ---> Running in 2265418ff3d2
Forcing web requests to allow TLS v1.2 (Required for requests to Chocolatey.org)
Getting latest version of the Chocolatey package for download.
Not using proxy.
Getting Chocolatey from https://community.chocolatey.org/api/v2/package/chocolatey/2.2.2.
Downloading https://community.chocolatey.org/api/v2/package/chocolatey/2.2.2 to C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.zip
Not using proxy.
Extracting C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\chocoInstall\chocolatey.zip to C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\chocoInstall
Installing Chocolatey on the local machine
The registry key for .Net 4.8 was not found or this is forced
Downloading 'https://download.visualstudio.microsoft.com/download/pr/2d6bb6b2-226a-4baa-bdec-798822606ff1/8494001c276a4b96804cde7829c04d7f/ndp48-x86-x64-allos-enu.exe' to 'C:\Users\ContainerAdministrator\AppData\Local\Temp\ndp48-x86-x64-allos-enu.exe' - the installer is 100+ MBs, so this could take a while on a slow connection.
Installing 'C:\Users\ContainerAdministrator\AppData\Local\Temp\ndp48-x86-x64-allos-enu.exe' - this may take awhile with no output.
.NET Framework 4.8 was installed, but a reboot is required. 
 Please reboot the system and try to install/upgrade Chocolatey again.
At C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\chocoInstall\t
ools\chocolateysetup.psm1:815 char:11
+           throw ".NET Framework 4.8 was installed, but a reboot is re ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (.NET Framework ...ocolatey ag
   ain.:String) [], RuntimeException
    + FullyQualifiedErrorId : .NET Framework 4.8 was installed, but a reboot i
   s required.
 Please reboot the system and try to install/upgrade Chocolatey again.

The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; Set-ExecutionPolicy Bypass -Scope Process -Force;     [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;     iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'));         choco install -y python3' returned a non-zero code: 1
```

I am using branch _ipy3-wip_, but a similar error happens on branch _Docker_ (for ipy 2.7).

**Comment by slozier** [comment]
I've got a newer Docker file which I can push this evening.

**Comment by BCSharp** [comment]
If you have some new progress for ipy3-wip, I'd be happy to see it too, and hopefully avoid duplication of effort. I have just started looking into ironclad and then later discovered the ipy3-wip branch; for some reason my github ironclad clone was claiming being "up-to-date" without carrying this branch. I'm happy to see that you accomplished much more than what I was able to in a few past days (which was mostly getting familiar with the ironclad structure, learning about scons, and tweaking SConstruct).

Question: are we dropping support for 32-bit ironclad for good? (personal preference: it would be great)

**Comment by slozier** [comment]
I've been playing around trying various things and getting familiar with the codebase. I did manage to get test_hashlib passing with the CPython _hashlib library. Currently trying to get numpy (1.11.0) to load. It's all very rough and have not gotten around to cleaning things up, but I've push whatever I have to [some other branch](https://github.com/slozier/ironclad/tree/wip).

**Comment by slozier** [comment]
I guess I forgot to answer your question about 32-bit. Yes I was planning on dropping 32-bit support for Ironclad.

Other things that might be of interest:
- For the stubs I've been using CPython 3.4.4
- I added the Clang workload to the Dockerfile because I was considering using it instead of gcc (to get pdb files) but couldn't figure out how to get scons to use it (not that I tried very hard).
- I've been using Visual Studio outside of Docker to debug:
  1. Build in Docker with `scons mode=debug`
  2. In VS I use IronPython solution and launch IronPythonConsole with the working directory `ironclad\build`
  3. My test file looks like:
```py
import ironclad
import sys

sys.path.append(r"C:\Python34\DLLs")
import _hashlib

sys.path.insert(0, r"R:\repos\github\ironpython3\Src\StdLib\Lib")

import unittest
unittest.main(module="test.test_hashlib", verbosity=2)
```

Let me know if you have any questions! Feel free to push stuff ipy3-wip branch (I'm assuming you have access but let me know if you don't).

**Comment by BCSharp** [comment]
Thanks a lot, I've managed build your Docker image and get `scons test` to run (15 errors, 1 failure).

* I am also using CPython 3.4.4.
* In my experiments, I replaced gcc/pexports with msvc/dumpbin; my goal was to remove the dependency on MinGW. I chose msvc because this is what [CPython 3.4 is reportedly compiled with](https://wiki.python.org/moin/WindowsCompilers), and I assumed that the wheels of various packages for Python 3.4 are using it too. I got scons working but not the tests, when I discovered your wip branch. The problem with msvc is that only 32-bit version seems to be freely downloadable, the 64-bit version requires a paid (?) licence. I do have an old Visual Studio 2010 licence lying around but still, not ideal for an open source project. Clang sounds promising, I didn't know it now comes with VS build tools; however, will it be able to generate binaries that link against msvcrt 10.0?
* I will play around with `test_hashlib` more in the coming days. I'm sure I will have more questions then.

I am closing this Issue as resolved (although the _Docker_ branch still has it) since I don't intend to work on 2.7. Unless you intend to merge _Docker_ into _master_... It would resolve #10.

**Comment by BCSharp** [comment]
@slozier, I am struggling with getting your test file to work. My local paths to Python 3.4 and IronPython workdir are slightly different (for the record, `C:\Tools\Python34` and `C:\Code\ironlang\ironpython3.worktrees\ironclad` respectively), but the rest is identical.

I get a `ValueError` from `ntpath.abspath()`:
```
Traceback (most recent call last):
  File "test_hashlib.py", line 5, in <module>
  File "<string>", line 17, in load_module
  File "C:\Code\ironlang\ironpython3.worktrees\ironclad\bin\Debug\net462\../../../Src/StdLib/Lib\ntpath.py", line 547, in abspath
ValueError: Specified path is invalid.
```

When I put `print("path is:'%s'" % path)` on that line, I get a printout of totally legitimate paths, until the last one being a weirdo:
```
path is:'C:\Code\ironlang\ironpython3.worktrees\ironclad\bin\Debug\net462\lib\os.py'
path is:'C:\Code\ironlang\ironpython3.worktrees\ironclad\bin\Debug\net462\../../../Src/StdLib/Lib\stat.py'
path is:'C:\Code\ironlang\ironpython3.worktrees\ironclad\bin\Debug\net462\../../../Src/StdLib/Lib\ntpath.py'
path is:'C:\Code\ironlang\ironpython3.worktrees\ironclad\bin\Debug\net462\../../../Src/StdLib/Lib\_sitebuiltins.py'
path is:'C:\Code\ironlang\ironpython3.worktrees\ironclad\bin\Debug\net462\../../../Src/StdLib/Lib\_weakrefset.py'
path is:'C:\Code\ironlang\ironpython3.worktrees\ironclad\bin\Debug\net462\../../../Src/StdLib/Lib\site.py'
path is:'C:\Code\ironlang\ironpython3.worktrees\ironclad\bin\Debug\net462\../../../Src/StdLib/Lib\abc.py'
path is:'C:\Code\ironlang\ironpython3.worktrees\ironclad\bin\Debug\net462\../../../Src/StdLib/Lib\genericpath.py'
path is:'C:\Code\ironlang\ironpython3.worktrees\ironclad\bin\Debug\net462\../../../Src/StdLib/Lib\_collections_abc.py'
path is:'C:\Code\ironlang\ironpython3.worktrees\ironclad\bin\Debug\net462\lib'
path is:'C:\Code\ironlang\ironpython3.worktrees\ironclad\bin\Debug\net462\lib'
path is:'C:\Code\ironlang\ironpython3.worktrees\ironclad\bin\Debug\net462\DLLs'
path is:'C:\Code\ironlang\ironpython3.worktrees\ironclad\bin\Debug\net462\../../../Src/StdLib/Lib'
path is:'C:\Code\ironlang\ironpython3.worktrees\ironclad\bin\Debug\net462\ipy.exe'
path is:'C:\Code\ironlang\ironpython3.worktrees\ironclad\bin\Debug\net462\ipy.exe'
path is:'C:\Code\ironlang\ironpython3.worktrees\ironclad\bin\Debug\net462\ipy.exe'
path is:'C:\Code\ironlang\ironpython3.worktrees\ironclad\bin\Debug\net462'
path is:'C:\Code\ironlang\ironpython3.worktrees\ironclad\bin\Debug\net462'
path is:'C:\Code\ironlang\ironpython3.worktrees\ironclad\Src\StdLib\Lib\keyword.py'
path is:'C:\Tools\Python34\DLLs\_hashlib.pyd'
path is:'test_hashlib.py'
path is:'C:\Tools\Python34\DLLs\_hashlib.pyd'
path is:'C:\Code\ironlang\ironpython3.worktrees\ironclad\Src\StdLib\Lib\genericpath.py'
path is:'C:\Tools\Python34\DLLs\_hashlib.pyd'
path is:'C:\Code\ironlang\ironpython3.worktrees\ironclad\Src\StdLib\Lib\encodings\cp1252.py'
path is:'C:\Tools\Python34\DLLs\_hashlib.pyd'
path is:'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, System.Buffers, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, System.Memory, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, System.Numerics.Vectors, Version=4.1.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

Ever seen anything like that? Any idea what is going on? I suppose `load_module` should not try to load `mscorlib` et al.?

**Comment by slozier** [comment]
Yes that does seem familiar. I think it's the loader in `INSTALL_IMPORT_HOOK_CODE.py`:
https://github.com/slozier/ironclad/blob/91ed9f83f1c87d46e9d6e5785ae36ea0631e9cb9/data/snippets/py/INSTALL_IMPORT_HOOK_CODE.py#L17-L21

I just added a try/except in my branch to get past the issue, but there has to be a cleaner way.

**Comment by BCSharp** [comment]
Thanks for the tip. It seems that the `Loader` does not understand CLR namespace tracker pseudotypes. I solved it by filtering modules on `type(m).__name__ != 'namespace#'`; unless you know a more idiomatic way to detect namespace trackers from within the Python code, I intend to check this into `py34-wip`. (I also intend to rename `MetaImporter` to `PydImporter` since this is what it does and the name is visible from Python user code. But Python 3.4 bring in more changes to the import machinery so I expect more changes here too).

Then I hit more errors down the road. I was working on `py34-wip`, not your private `wip` because it had a few more tests passing, so I assumed that your wip is less stable. But your wip does load `_hashlib` OK and all but one test pass. I will use it now more often as reference if I get stuck on something again.

**Comment by slozier** [comment]
Can't think of something better than the type name check (definitely better than my try/except 😄). `py34-wip` is more "stable" but it's a lie since it's using the CPython 2.7 code in the stubs. I ended up deciding to remove all the stubs and add them back in as needed in my `wip` branch.

Looks like I had these lines commented out in test_hashlib so probably where you're getting the failure?
```py
out = pbkdf2(digest_name, memoryview(password), memoryview(salt), rounds, dklen)
self.assertEqual(out, expected) # this is missing in the CPython test...
```

**Comment by BCSharp** [comment]
> Looks like I had these lines commented out in test_hashlib so probably where you're getting the failure?

That's right.

> I ended up deciding to remove all the stubs and add them back in as needed in my `wip` branch.

Does it mean that all stubs that exist in your `wip` branch are from 3.4 now? Maybe I should work on top of your branch?

**Comment by slozier** [comment]
> Does it mean that all stubs that exist in your `wip` branch are from 3.4 now? Maybe I should work on top of your branch?

Wait a minute. I'm confusing myself! Looks like I did remove the 2.7 stubs from the `ipy3-wip` branch! So that means all the includes in that branch are from 3.4.4 and in my `wip` branch adds some `.c` files from 3.4.4.
